feat: support twenty batch endpoints
openint-dev/openint pull request #19
Opened 2024-06-05 07:40 UTC by Nabhag8848

### Description

- [ ] To be merged after publishing sdk, need to push lock file changes on sdk version upgrade.

2024-06-06 08:11 UTC, basinhr requested changes

2024-06-06 08:11 UTC, basinhr commented on connectors/connector-revert/server.ts
> +        yield* PipeRecordsInStream(name, stream.fields ?? [], sState) // TODO(@jatin): update this.
why the capital function name?

2024-06-06 08:11 UTC, basinhr commented on connectors/connector-revert/server.ts
> +            [stream]: records,
This doesn't quite look right. We need to emit individual records, see example in QBO/server

2024-06-10 15:34 UTC, tonyxiao requested changes
We do not want to emit arrays of items, but individual items themselves. 
 
 <img width="848" alt="image" src="https://github.com/openint-dev/openint/assets/696842/ee760749-e22b-46c0-bfec-5e3d615d9eb3">
Please see `postgres/server.ts` for an example of how to collect individual events into arrays that can be batch inserted.

2024-07-01 11:14 UTC, jatinsandilya commented
@tonyxiao seems like the requested changes are made? Good to merge?

2024-07-09 10:21 UTC, merged